version: "3.7"
services:
  redis:
    image: ${IMAGE_REDIS}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    volumes:
      - ./redis-data:/data
    networks:
      - default
    restart: always
  postgres:
    image: ${IMAGE_POSTGRES}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
    restart: always
  nest:
    # image: ${IMAGE_NEST}
    build:
      context: ./csl-backend
      dockerfile: Dockerfile
    container_name: csl-backend
    environment:
      PORT: ${PORT_API}
      POSTGRES_PORT: ${PORT_DB}

      # Enable if want local database
      # POSTGRES_HOST: postgres
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_DB: ${DB_NAME}

      # Enable if want dedicated database
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    ports:
      - ${PORT_NEST}:${PORT_NEST}
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    networks:
      - default
    restart: always
    command: npm run start:dev
  next:
    # image: ${IMAGE_NEXT}
    build:
      context: ./csl-frontend
      dockerfile: Dockerfile
    container_name: csl-frontend
    environment:
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      NEXT_BACKEND_URL: ${NEXT_BACKEND_URL}
    ports:
      - ${PORT_NEXT}:${PORT_NEXT}
    depends_on:
      - postgres
      - nest
    networks:
      - default
    restart: always
    command: npm run dev
volumes:
  postgres-data:
  redis-data:
