version: "3.7"
services:
  postgres:
    image: ${IMAGE_POSTGRES}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - default
    restart: always
  nest:
    # image: ${IMAGE_NEST}
    build:
      context: ./csurf-league-backend
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT_API}
      POSTGRES_PORT: ${PORT_DB}

      # Enable if want local database
      # POSTGRES_HOST: postgres
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_DB: ${DB_NAME}

      # Enable if want dedicated database
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${PORT_NEST}:${PORT_NEST}
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - default
    restart: always
    command: npm run start:dev
  next:
    # image: ${IMAGE_NEXT}
    build:
      context: ./csurf-league-frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      NEXT_BACKEND_URL: ${NEXT_BACKEND_URL}
    ports:
      - ${PORT_NEXT}:${PORT_NEXT}
    depends_on:
      - postgres
      - nest
    networks:
      - default
    restart: always
    command: npm run dev
volumes:
  pgdata:
